### ISSUE TITLE
Np.float_ Error

### ISSUE THREAD

**Issue by lmac-amog** [NREL/MoorPy#26]
## Description
System creation throws an error - I believe this is because np.float_ is now out of use as of numpy 2.0. Fixed this locally by swapping to np.float64 across all functions in moorpy.

### Steps to reproduce issue
import moorpy as MP

MP_sys = MP.System()

### Current behavior
Throws an attribute error:
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.. Did you mean: 'float16'?
The error originates from the Body() function.

### Expected behavior
No error

### Code versions
- Python 3.10
- contourpy-1.2.1 
- cycler-0.12.1 
- fonttools-4.53.1 
- kiwisolver-1.4.5 
- matplotlib-3.9.1 
- moorpy-1.0.2 
- numpy-2.0.0 
- packaging-24.1 
- pillow-10.4.0
- pyparsing-3.1.2 
- python-dateutil-2.9.0.post0 
- pyyaml-6.0.1 
- scipy-1.14.0 
- six-1.16.0

**Comment by mattEhall** [comment]
We've addressed this by using basic python int/float equivalents instead.
