### ISSUE TITLE
Problem when reading input files

### ISSUE THREAD

**Issue by lucpavonese** [NREL/MoorPy#6]
Dear development team,

Similarly, as #3, I am also planning to use MoorPy to estimate the stiffness matrix of a given mooring system. However, I am having problems when trying to run the library.

I tried the master branch as well as the develop branch. The problem stated below was also observed in the most up-to-date version (commit b01c3c9). 

When I try to run my code, I get the following error: 
`ValueError: Point ID (1800000) out of bounds for line 1 end A attachment.`

The same error happens when I try to replicate the same code shown in #3 and the example "imported_system.py". I also tried to run the code in the imported_system.py example with the sample input file given in the documentation.

Therefore, I would like ask if there was any change in the way that the files are read that is not documented or if I somehow let something pass.

Thanks in advance!

**Comment by erickaloz** [comment]
Hello thanks for your feedback!  I recently pushed changes to the dev branch that update the input file format in "system.txt".  The example "imported_system.py" should run properly now.  Please let us know if you are still having issues!

**Comment by mattEhall** [comment]
Hi @lucpavonese,

To explain a little more, we had updated the dev branch of MoorPy to use the latest MoorDyn-style input file format (described [here](https://moordyn.readthedocs.io/en/latest/usage.html#the-v2-input-file-next-release)). This newer format has a different ordering of the columns in the Lines section. We have now updated the dev-branch documentation to clarify the latest format at https://moorpy.readthedocs.io/en/dev/usage.html

We hadn't yet updated the sample scripts and input file, which resulted in MoorPy reading in the Lines' unstretched lengths as the attached Point ID numbers. @erickaloz's commit https://github.com/NREL/MoorPy/commit/b01c3c92eafe8761b7fa2800411831733b915140 corrects the sample.txt input file for imported_system.py and I have now also corrected the manual_system.py example. Hopefully the dev branch examples are all consistent now.

Thanks for raising this issue.
Matt

**Comment by fnaos** [comment]
Hi all,

Thanks for the quick action.

I tried to run the imported_system.py example and now I get the following error:
`
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\anaconda3\\Lib\\site-packages\\MoorPy-0.9.0-py3.8.egg\\moorpy\\MoorProps_default.yaml'`
