### ISSUE TITLE
MoorProps in the __init__.py script

### ISSUE THREAD

**Issue by goharShoukat** [NREL/MoorPy#7]
Hi, 
I'm not sure why the functions in the MoorProps.py script were not included in the moorpy declaration. I've added it into my installation though. Thought it might have been skipped accidentally so flagging it here. 

Thanks!

**Comment by mattEhall** [comment]
Hi, sorry we overlooked your post! (We are still adjusting to other people using MoorPy.) Question for you on this: did you find there function calls to the MoorProps module in the code already leaded in by the MoorPy __init__ file, meaning that an error would be thrown? Or is this just a matter of convenience for a user to more easily call functions in MoorProps?
Thanks,
Matt

**Comment by goharShoukat** [comment]
I had to go into the respective library to pull the relevantt functions out. They didnt load up for me. Declaring it in the init file was important in my case because I am not the end-user and someone less experienced was going to run it.
